# Generated by Django 4.2.8 on 2024-03-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['user_info', 'access_token', 'code'], name='api_auth_so_user_in_eb96ba_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['phone_number', 'shipping_address'], name='api_auth_us_phone_n_4787b4_idx'),
        ),
    ]
