# Generated by Django 4.2.8 on 2024-03-19 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0004_socialaccount_api_auth_so_user_in_eb96ba_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='api_auth_cu_email_8af5db_idx',
        ),
        migrations.RemoveIndex(
            model_name='socialaccount',
            name='api_auth_so_user_in_eb96ba_idx',
        ),
    ]
