# Generated by Django 4.2.8 on 2024-03-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0006_socialaccount_api_auth_so_user_in_eb96ba_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='api_auth_cu_email_8af5db_idx'),
        ),
    ]
